# -*- coding: utf-8 -*-
"""line_bot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZxBAkgDdgNbKwFu8m-NH6vribwr_x9S
"""

from flask import Flask,request,abort
from linebot import LineBotApi,WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent,TextMessage,TextSendMessage
import pya3rt


app=Flask(__name__)

line_bot_api=LineBotApi('+4DTvR1ASCVG9/t/75nTNVL5y+iYVGw4J8+C846vajvStlC3R/iAcizJXK+xTGWwK9kS5+OGYQ8A2zojoKZjETrkp5yRdvRTxKZR4ZaeRSSURXD3m7kYnRFFX+M8nC1q+4G5wVC9nP44PricavcSgAdB04t89/1O/w1cDnyilFU=')

handler=WebhookHandler('91c5a6b9d407b6097ccae730c7e20887')

@app.route("/callback",methods=['POST'])
def callback():
  signature=request.headers["X-Line-Signature"]
  body=request.get_data(as_text=True)

  try:
    handler.handle(body,signature)
  except InvalidSignatureError:
    abort(400)

  return 'OK'

@handler.add(MessageEvent,message=TextMessage)
def handle_message(event):
  ai_message=talk_ai(event.message.text)
  line_bot_api.reply_message(event.reply_token,TextSendMessage(text=ai_message))

def talk_ai(word):
  apikey="DZZtuJemGM67NVNvYdQAFwdUwUS3WCWI"
  client=pya3rt.TalkClient(apikey)
  reply_message=client.talk(word)
  return reply_message['results'][0]['reply']

if __name__=='__main__':
    app.run()